name: Release build

on:
  push:
    branches: [ main ]
#  pull_request:
#    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: Make Build Dir
      run: mkdir build
    - name: Build
      run: go build -o ./build -v ./...
    - name: Build windows binary
      run: env GOOS=windows GOARCH=amd64 go build -o ./build/ht.exe
    - name: Upload Windows .exe
      uses: actions/upload-artifact@v2
      with:
        name: ht.exe
        path: ./build/ht.exe
    - name: Upload Linux binary
      uses: actions/upload-artifact@v2
      with:
        name: ht
        path: ./build/hunttools
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Development Build"
        files: |
          ./build/ht
          ./build/ht.exe
#    - name: Test
#      run: go test -v ./...
