name: Go

on:
  push:
    branches: [ main ]
#  pull_request:
#    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build
      run: go build -o ./linux/ht -v ./...
    - name: Build windows binary
      run: env GOOS=windows GOARCH=amd64 go build -o ./windows/ht.exe
#    - name: Test
#      run: go test -v ./...
