name: Release build

on:
  push:
    branches: [ main ]
#  pull_request:
#    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: Make Build Dir
      run: mkdir build
    - name: Build
      run: go build -o ./build/ht
    - name: Build windows binary
      run: env GOOS=windows GOARCH=amd64 go build -o ./build/ht.exe
    - name: Build macOS binary
      run: env GOOS=darwin GOARCH=amd64 go build -o ./build/ht_mac
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Development Build"
        files: |
          ./build/ht*
